version: "3.10"
services:
  docker-demo:
    image: docker-demo:latest
    working_dir: /app
    build: "./"
    restart: always
    command: "python -m flask run --port=5500"
    ports:
      - "5500:5500"
    public: true
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
